version: "3.1"

services:
  mysql:
    image: mysql:8.0.3  
  volumes:
  	- ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  	command: --init-file /docker-entrypoint-initdb.d/init.sql
  
  	ports:
    	- 3312:3306
  	environment:
    	MYSQL_DATABASE: services_db
    	MYSQL_ROOT_USER: admin
    	MYSQL_USER: admin
    	MYSQL_ROOT_PASSWORD: secret
    	MYSQL_PASSWORD: secret